### ISSUE TITLE
connected textures dont work (conquest texture pack)

### ISSUE THREAD

**Issue by Zeinoth** [Sildurs-shaders/sildurs-shaders.github.io#24]
Connected textures on rescourcepacks such as conquest reforged are broken when using sildurs. Is there any chance to fix this?
![2019-10-07_00 20 07](https://user-images.githubusercontent.com/55437557/66269765-62b1c000-e898-11e9-9bbb-4ba18b4344d3.png)
![2019-10-07_00 20 10](https://user-images.githubusercontent.com/55437557/66269766-634a5680-e898-11e9-85b2-8ac561c8ca1a.png)

**Comment by Sildurs-shaders** [comment]
You must change their block properties, they break if they're set to translucent.

**Comment by Zeinoth** [comment]
im just using the texture pack, can you explain in idiot terms what that means? also (i think) this is unrelated, but when using (any) shaders i get this weird de-rendering of chunks, is this caused by my graphics card?
![2019-10-08_00 19 33](https://user-images.githubusercontent.com/55437557/66315385-68bfa380-e961-11e9-8dc2-2fa8d13a1f71.png)

**Comment by Zeinoth** [comment]
(its worth noting that i am playing with mods)

**Comment by Sildurs-shaders** [comment]
Hm, it's a bit hard to explain since I never did it myself, but textures in resourcepacks should have a block.properties file to define it's type, setting this to translucent breaks the textures in vibrant shaders, so it must be changed. You should be able to find out more about this in my minecraft forum post, there where a few discussions about it.
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291396-1-7-10-1-14-4-sildurs-shaders-pc-mac-intel

**Comment by Zeinoth** [comment]
ok last question i swear, i saw you said "If you don't see rain reflections make sure optifine is up to date. Still nothing? Disable the biome check in the ingame options.", where can i find this option?

**Comment by Sildurs-shaders** [comment]
Just in the ingame options, I think it's the reflections section. There should be an option to enable rain reflections in any biomes.
